name: GlobalToast
main: SVega9848\GlobalToast\Core\Main
version: 0.1.0
api: 4.0.0
author: SVega
description: Broadcast toast announcements to everyone in the server!

permissions:
  globaltoast.cmd:
    description: Broadcast toast announcements to everyone in the server!
    default: op
  globaltoast.use:
    default: op
    description: Get Access to Use the {player} Variable!
